name: Análise branch main SonarCloud

on:
  push:
    branches: [ "main" ]

jobs:
  sonar-analysis:
    name: Análise de Qualidade SonarCloud
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Configurar Java 17 (SonarScanner)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Encontrar arquivo da Solution (.sln)
        id: find_sln
        run: echo "sln_path=$(find . -name '*.sln' -print -quit)" >> $GITHUB_OUTPUT

      - name: SonarCloud - Iniciar Análise
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin \
            /k:"joaosena19_fiap-12soat-projeto-fase-4-auth-lambda" \
            /o:"joaosena19" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml"

      - name: Restaurar dependências
        run: dotnet restore ${{ steps.find_sln.outputs.sln_path }}

      - name: Build (Release)
        run: dotnet build ${{ steps.find_sln.outputs.sln_path }} --no-restore --configuration Release

      - name: Testes com Cobertura
        run: |
          dotnet test ${{ steps.find_sln.outputs.sln_path }} \
            --no-build --configuration Release --verbosity minimal \
            --collect:"XPlat Code Coverage" \
            --results-directory ./TestResults \
            --settings src/Tests/coverlet.runsettings \
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        continue-on-error: true
        env:
          Jwt__Key: "dummy-super-secret-key-for-testing-purposes-only"
          Jwt__Issuer: "OficinaMecanicaApi"
          Jwt__Audience: "AuthorizedServices"
          ApiCredentials__ClientId: "test-client"
          ApiCredentials__ClientSecret: "test-secret"

      - name: SonarCloud - Finalizar Análise
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
